from django.db import models
from authentication.models import User
from helpers.models import TrackingModel
# Create your models here.


class CV(TrackingModel):
    templateNumber = models.CharField(max_length=10)
    # cv_avatar = models.CharField(max_length=100, default="/static/images/girl.jpg")
    cv_avatar = models.CharField(max_length=100, default="/static/images/flag2.png")
    title = models.CharField(max_length=35, default='Ngo Minh Dai')
    cv_current_job = models.CharField(max_length=255, default='Web Developer')
    cv_contact_info = models.CharField(max_length=255, default='Contact Info')
    cv_contact_info_phone = models.CharField(max_length=255, default='0358563350')
    cv_contact_info_gender = models.CharField(max_length=255, default='Male')
    cv_contact_info_gmail = models.CharField(max_length=255, default='example@gmail.com')
    cv_contact_info_website = models.CharField(max_length=255, default='bestcv.com')
    cv_contact_info_facebook = models.CharField(max_length=255, default='fb.com')
    cv_contact_info_home = models.CharField(max_length=255, default='Vung Tau, Viet Nam')

    cv_education = models.CharField(max_length=255, default="education")
    cv_count_education = models.CharField(max_length=10, default=1)
    cv_degree1 = models.CharField(max_length=255, default='Master Degree in Computer Science')
    cv_graduation_time1 = models.CharField(max_length=255, default='2019 - 2021')
    cv_graduation_school1 = models.CharField(max_length=255, default='HCM University of Technology')
    cv_degree2 = models.CharField(max_length=255, default='')
    cv_graduation_time2 = models.CharField(max_length=255, default='')
    cv_graduation_school2 = models.CharField(max_length=255, default='')
    cv_degree3 = models.CharField(max_length=255, default='')
    cv_graduation_time3 = models.CharField(max_length=255, default='')
    cv_graduation_school3 = models.CharField(max_length=255, default='')

    cv_lang = models.CharField(max_length=255, default='Languages')
    cv_count_lang = models.CharField(max_length=10, default=2)

    cv_lang1 = models.CharField(max_length=255, default='English')
    cv_lang1_expert = models.CharField(max_length=255,default='80')
    cv_lang2 = models.CharField(max_length=255,default='Vietnamese')
    cv_lang2_expert = models.CharField(max_length=255,default='95')
    cv_lang3 = models.CharField(max_length=255,default='')
    cv_lang3_expert = models.CharField(max_length=255,default='')
    cv_lang4 = models.CharField(max_length=255,default='')
    cv_lang4_expert = models.CharField(max_length=255,default='')
    cv_lang5 = models.CharField(max_length=255,default='')
    cv_lang5_expert = models.CharField(max_length=255,default='')

    cv_profile = models.CharField(max_length=255, default='Profile')

    cv_experience = models.CharField(max_length=255, default='Experience')
    cv_count_experience = models.CharField(max_length=10, default=2)

    cv_company_role1 = models.CharField(max_length=255, default='Product Developer')
    cv_job_description1 = models.TextField(default='Have some projects with UX/UI Direction, Web development and Mobile app development.')
    cv_company_name1 = models.CharField(max_length=255, default='BestCV Company')
    cv_working_time1 = models.CharField(max_length=255, default='03/2015 - 03/2018')
    cv_company_role2 = models.CharField(max_length=255, default='Full-stack Developer')
    cv_job_description2 = models.TextField(default='Build and deploy projects, participate in the development of projects using artistic Javascript, Django API.')
    cv_company_name2 = models.CharField(max_length=255, default='BestCV Company')
    cv_working_time2 = models.CharField(max_length=255, default='03/2018 - NOW')
    cv_company_role3 = models.CharField(max_length=255, default='')
    cv_job_description3 = models.TextField(default='')
    cv_company_name3 = models.CharField(max_length=255, default='')
    cv_working_time3 = models.CharField(max_length=255, default='')
    cv_company_role4 = models.CharField(max_length=255, default='')
    cv_job_description4 = models.TextField(default='')
    cv_company_name4 = models.CharField(max_length=255, default='')
    cv_working_time4 = models.CharField(max_length=255, default='')
    cv_company_role5 = models.CharField(max_length=255, default='')
    cv_job_description5 = models.TextField(default='')
    cv_company_name5 = models.CharField(max_length=255, default='')
    cv_working_time5 = models.CharField(max_length=255, default='')

    cv_skill = models.CharField(max_length=255,default='Professional Skills')
    cv_count_skill = models.CharField(max_length=10, default=4)
    cv_skill1 = models.CharField(max_length=255, default='Algorithm')
    cv_skill1_expert = models.CharField(max_length=255,default='80')
    cv_skill2 = models.CharField(max_length=255, default='PHP')
    cv_skill2_expert = models.CharField(max_length=255,default='95')
    cv_skill3 = models.CharField(max_length=255, default='Javascript')
    cv_skill3_expert = models.CharField(max_length=255, default='70')
    cv_skill4 = models.CharField(max_length=255, default='Django')
    cv_skill4_expert = models.CharField(max_length=255, default='75')
    cv_skill5 = models.CharField(max_length=255, default='')
    cv_skill5_expert = models.CharField(max_length=255, default='')
    cv_skill6 = models.CharField(max_length=255, default='')
    cv_skill6_expert = models.CharField(max_length=255, default='')
    cv_skill7 = models.CharField(max_length=255, default='')
    cv_skill7_expert = models.CharField(max_length=255, default='')
    cv_skill8 = models.CharField(max_length=255, default='')
    cv_skill8_expert = models.CharField(max_length=255, default='')
    cv_skill9 = models.CharField(max_length=255, default='')
    cv_skill9_expert = models.CharField(max_length=255, default='')
    cv_skill10 = models.CharField(max_length=255, default='')
    cv_skill10_expert = models.CharField(max_length=255, default='')

    cv_interest = models.CharField(max_length=255, default='interest')
    cv_count_interest = models.CharField(max_length=10, default=3)
    cv_interest1 = models.CharField(max_length=255, default='Reading')
    cv_interest2 = models.CharField(max_length=255, default='Singing')
    cv_interest3 = models.CharField(max_length=255, default='Running')
    cv_interest4 = models.CharField(max_length=255, default='')
    cv_interest5 = models.CharField(max_length=255, default='')
    cv_interest6 = models.CharField(max_length=255, default='')
    cv_interest7 = models.CharField(max_length=255, default='')
    cv_interest8 = models.CharField(max_length=255, default='')
    cv_interest9 = models.CharField(max_length=255, default='')
    cv_interest10 = models.CharField(max_length=255, default='')
  
    cv_cer = models.CharField(max_length=255, default='Awards & Certifications')
    cv_count_cer = models.CharField(max_length=10, default=2)
    cv_cer_year1 = models.CharField(max_length=255, default='2017-2018')
    cv_cer_name1 = models.CharField(max_length=255, default='BestCV Scholarship in 2nd semester 2016-2017 and 1st semester 2017-2018.')
    cv_cer_year2 = models.CharField(max_length=255, default='2021')
    cv_cer_name2 = models.CharField(max_length=255, default='TOEIC Certificate with score 800 issued by BestCV')
    cv_cer_year3 = models.CharField(max_length=255, default='')
    cv_cer_name3 = models.CharField(max_length=255, default='')
    cv_cer_year4 = models.CharField(max_length=255, default='')
    cv_cer_name4 = models.CharField(max_length=255, default='')
    cv_cer_year5 = models.CharField(max_length=255, default='')
    cv_cer_name5 = models.CharField(max_length=255, default='')

    cv_activity = models.CharField(max_length=255, default='activity')
    cv_count_activity = models.CharField(max_length=10, default=1)

    cv_activity_company_role1 = models.CharField(max_length=255, default='Member of BestCV Ambassador')
    cv_activity_job_description1 = models.TextField(default='Organize monthly events, network with HCMUT students and share how to hunt scholarships and support to find appropriate job or careers.')
    cv_activity_company_name1 = models.CharField(max_length=255, default='BestCV - EDUCATION TALK 2021')
    cv_activity_working_time1 = models.CharField(max_length=255, default='Jan 2021 - Feb 2021')
    cv_activity_company_role2 = models.CharField(max_length=255, default='')
    cv_activity_job_description2 = models.TextField(default='')
    cv_activity_company_name2 = models.CharField(max_length=255, default='')
    cv_activity_working_time2 = models.CharField(max_length=255, default='')
    cv_activity_company_role3 = models.CharField(max_length=255, default='')
    cv_activity_job_description3 = models.TextField(default='')
    cv_activity_company_name3 = models.CharField(max_length=255, default='')
    cv_activity_working_time3 = models.CharField(max_length=255, default='')
    cv_activity_company_role4 = models.CharField(max_length=255, default='')
    cv_activity_job_description4 = models.TextField(default='')
    cv_activity_company_name4 = models.CharField(max_length=255, default='')
    cv_activity_working_time4 = models.CharField(max_length=255, default='')
    cv_activity_company_role5 = models.CharField(max_length=255, default='')
    cv_activity_job_description5 = models.TextField(default='')
    cv_activity_company_name5 = models.CharField(max_length=255, default='')
    cv_activity_working_time5 = models.CharField(max_length=255, default='')
    
    description = models.TextField(default='Take advantages of sales skills & experience and understanding of market to become a professional Sales Staff and bring a lot value to Customers. From that, I will contribute to development of BestCV Company.')
    is_published = models.BooleanField(default=False)
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
